# Generated by Django 3.0 on 2020-02-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=None, max_length=14, null=True, verbose_name='Phone'),
        ),
    ]
