# Generated by Django 3.0 on 2020-02-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'In'), (2, 'Out')], db_index=True, default=None, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=19, verbose_name='Value'),
            preserve_default=False,
        ),
    ]
