# Generated by Django 3.0 on 2020-02-11 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_auto_20200210_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='inserted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 10, 21, 19, 17, 776450), verbose_name='Inserted at'),
            preserve_default=False,
        ),
    ]
