# Generated by Django 3.0 on 2020-02-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_transaction_inserted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
    ]
